version: '3'
services:
  db:
    build: ./ebaywatch-db
    environment:
      - PGDATA=/data/db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=ebaywatch
    volumes:
      - /data/ebaywatcher/db_container:/data:rw
    networks:
      - watchernet
  proxy:
    build: ./ebaywatch-proxy
    environment:
      - PROXYPORT=8000
    networks:
      - watchernet
  watcher:
    build: ./ebaywatcher
    depends_on:
      - db
      - proxy
    environment:
      - CONFIGMODE=docker # Inform application it should use paths & configuration related to docker mode
      - PROXYPATH=socks5://proxy:8000
      - CONNECTIONSTRING=Server=db;port=5432;Database=ebaywatch;User Id=dbuser;Password=password;Timeout=5;CommandTimeout=60
    volumes:
      - /data/ebaywatcher/ebaydata:/data:rw
    networks:
      - watchernet
    logging:
      driver: "json-file" # We store our own logs, but let docker keep some for reporting through docker-compose
      options:
        max-size: "200k" # Do limit how much is stored though.
        max-file: "10"
networks:
  watchernet:
