
name: Run Pytest
on: push
jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        python-version: ["3.9", "3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements-base.txt
          pip install --user -r requirements-dev.txt
      - name: Build site
        run: |
          cd preordain/static/preordain
          npm install
          npm run dev
      - name: Test with pytest
        env:
          PROJECT: Preordain
          DB_EXISTS: true
          TESTING: true
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          TCG_SALES: "2022-12-14 05:59:07.360573+00:00"
        run: |
          pytest --cov=tests/
