
name: Run PyTest
on: [push]
jobs:
  ${{matrix.os.name}} ${{matrix.os.python-version}}:

    runs-on: ${{matrix.os.host}}
    strategy:
      matrix:
        os: 
        - name: Windows 11 (${{matrix.os.python-version}})
          host: windows-latest
          python-version: ['3.9', '3.10', '3.11']
        - name: Mac OS 12 (${{matrix.os.python-version}})
          host: macos-latest
          python-version: ['3.9', '3.10', '3.11']
        - name: Ubuntu (${{matrix.os.python-version}})
          host: ubuntu-latest
          python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.os.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.os.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install --user -r requirements.txt; fi
      - name: Test with pytest
        env:
          DB_EXISTS: true
          TESTING: true
          DB_HOST: ${{ secrets.DB_HOST }}
          TCG_SALES: "2022-12-14 05:59:07.360573+00:00"
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          pytest --cov=tests/
